## Data Process

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [5]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


## Train Model

In [8]:
clf = KNeighborsClassifier(n_neighbors=5, algorithm="kd_tree")
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree')

In [12]:
clf.get_params()

{'algorithm': 'kd_tree',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

## Predict

In [20]:
clf.predict(X_test)

array([1, 0, 0, 0, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2, 0, 0, 2,
       2, 0, 0, 2, 1, 0, 0, 0])

In [21]:
clf.predict_proba(X_test)

array([[0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.4, 0.6],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.8, 0.2],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ]])

In [22]:
clf.score(X_test, y_test)

1.0

In [23]:
clf.kneighbors(X_test)

(array([[0.2       , 0.24494897, 0.34641016, 0.37416574, 0.41231056],
        [0.2236068 , 0.3       , 0.31622777, 0.33166248, 0.34641016],
        [0.2236068 , 0.3       , 0.3       , 0.31622777, 0.31622777],
        [0.14142136, 0.24494897, 0.24494897, 0.3       , 0.33166248],
        [0.24494897, 0.37416574, 0.38729833, 0.41231056, 0.47958315],
        [0.42426407, 0.45825757, 0.46904158, 0.53851648, 0.57445626],
        [0.48989795, 0.50990195, 0.50990195, 0.51961524, 0.64031242],
        [0.31622777, 0.42426407, 0.42426407, 0.42426407, 0.47958315],
        [0.17320508, 0.2236068 , 0.3       , 0.31622777, 0.31622777],
        [0.53851648, 0.54772256, 0.66332496, 0.678233  , 0.7       ],
        [0.55677644, 0.6       , 0.6164414 , 0.6244998 , 0.66332496],
        [0.2236068 , 0.3       , 0.43588989, 0.45825757, 0.50990195],
        [0.2236068 , 0.31622777, 0.31622777, 0.34641016, 0.38729833],
        [0.26457513, 0.42426407, 0.45825757, 0.45825757, 0.46904158],
        [0.17320508,